# Generated by Django 5.1.7 on 2025-03-26 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_taken', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='philosopher',
            name='state',
            field=models.CharField(choices=[('Thinking', 'Thinking'), ('Hungry', 'Hungry'), ('Eating', 'Eating')], max_length=50),
        ),
        migrations.AddField(
            model_name='philosopher',
            name='left_fork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='left_philosopher', to='polls.fork'),
        ),
        migrations.AddField(
            model_name='philosopher',
            name='right_fork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='right_philosopher', to='polls.fork'),
        ),
    ]
