# Generated by Django 5.1.7 on 2025-03-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_create_forks'),
    ]

    operations = [
    ]
